#!/bin/zsh

#Attempt 1
# sed --in-place='.sedbk' 's/user_pref("layout.css.devPixelsPerPx", "[0-9.]*");/user_pref("layout.css.devPixelsPerPx", "2.0");/' ~/.mozilla/firefox/yc2isdec.default/prefs.js

#Attempt 2
# For Firefox
#echo 'user_pref("layout.css.devPixelsPerPx", "2.0");' > ~/.mozilla/firefox/yc2isdec.default/user.js

# gsettings
# gsettings set org.gnome.desktop.interface text-scaling-factor 2.0

# Attempt 3
gsettings set org.gnome.desktop.interface scaling-factor 2
gsettings set org.gnome.desktop.interface text-scaling-factor 1.0
