#!/bin/bash

excludefile=/home/wendell/scripts/ipodexclude.txt

ipodloc=/media/ipod

if [[ ! -d $ipodloc/.rockbox ]] ; then
    echo "MOUNTING..."
    sudo mount -t vfat '/dev/disk/by-id/usb-Apple_iPod_00000098DCFB-0:0-part2' $ipodloc -o'uid=1001,gid=1001,shortname=mixed'
    mounted=True
    echo "------------------------------------------------"
fi

if [[ ! -d $ipodloc/.rockbox ]] ; then
    echo "Device does not exist. Is the ipod plugged in?"
    exit 2
fi

/home/wendell/scripts/mygpo.py

command="python /home/wendell/scripts/id3simple.py"
echo $command
$command
echo "------------------------------------------------"

# use -n for dry-run
command="rsync -vrlt --modify-window=3 --delete-excluded --exclude-from "$excludefile" /data/mp3/ $ipodloc/audio"
echo $command
$command

df -BM $ipodloc

if [[ -n $mounted ]] ; then
    echo "EJECTING..."
    sudo eject $ipodloc
fi
echo "Done!"
