#!/bin/bash

excludefile=/home/wendell/scripts/ipodexclude.txt

/home/wendell/scripts/mygpo.py

command="python /home/wendell/scripts/id3simple.py"
echo $command
$command
echo "------------------------------------------------"

if [[ ! -d /media/NIGEL/.rockbox ]] ; then
    echo "MOUNTING..."
    sudo mount -t vfat '/dev/disk/by-id/usb-Apple_iPod_00000098DCFB-0:0-part2' /media/NIGEL -o'uid=1001,gid=1001,shortname=mixed'
    mounted=True
    echo "------------------------------------------------"
fi

if [[ ! -d /media/NIGEL/.rockbox ]] ; then
    echo "Device does not exist. Is the ipod plugged in?"
    exit 2
fi

# use -n for dry-run
command="rsync -vrlt --modify-window=3 --delete-excluded --exclude-from "$excludefile" /data/mp3/ /media/NIGEL/audio"
echo $command
$command

df -BM /media/NIGEL

if [[ -n $mounted ]] ; then
    echo "EJECTING..."
    sudo eject /media/NIGEL
fi
echo "Done!"