#!/bin/python

import mutagen.mp3 as mp3
import os.path as path
import os

topdir='/win/MP3/'
maindir='/win/MP3/'

lastinfo=None

def trk(strng):
    if "/" in strng:
        return strng.split('/')[0]
    else:
        return strng

def getfname(fname, i):
    try:
        title=str(i['TIT2'])[:30]
    except KeyError, e:
        print "ERROR1:", e, fname
        title = None
    except HeaderNotFoundError, e:
        return fname
    
    if title:
        newfname = title + '.mp3'
    else:
        newfname = fname
    
    try:
        track=trk(str(i['TRCK']))
    except KeyError, e:
        print "ERROR2:", e, fname
        track=None
    except HeaderNotFoundError, e:
        return newfname
    
    if track:
        return track + '-' + newfname

def getdirname(dirname, i):
    try:
        comp =i['TCMP']
    except KeyError:
        comp = 0
    except HeaderNotFoundError:
        return dirname
    try:
        genre=str(i['TCON'])[:30]
        album=str(i['TALB'])[:30]
        artst=str(i['TPE1'])[:30]
    except KeyError, e:
        print e, fname
        genre = album = artst = None
    #~ for k in lastinfo.keys():
        #~ print "    ",repr(k), repr(lastinfo[k])[:40]
    newdir = dirname
    newfname = fname
    
    if album and artst:
        newdir = path.join(topdir, artst, album)
    
    if genre and album and artst and 'podcast' in genre.lower():
        newdir = path.join(topdir, 'Podcast', artst, album)
    
    return (newdir, newfname)

def getnewnames(dirname, fname):
    global lastinfo
    fullname=path.join(dirname, fname)
    try:
        i=mp3.MP3(fullname)
    except Exception, e:
        return (dirname, fname)
    lastinfo=i
    try:
        title=str(i['TIT2'])[:30]
        track=trk(str(i['TRCK']))
    except KeyError, e:
        print "ERROR3:", e, fname
        title = track = None
    try:
        comp =i['TCMP']
    except KeyError:
        comp = 0
    try:
        genre=str(i['TCON'])[:30]
        album=str(i['TALB'])[:30]
        artst=str(i['TPE1'])[:30]
    except KeyError, e:
        print "ERROR4:", e, fname
        genre = album = artst = None
    #~ for k in lastinfo.keys():
        #~ print "    ",repr(k), repr(lastinfo[k])[:40]
    newdir = dirname
    newfname = fname
    if genre and album and artst and 'podcast' in genre.lower():
        newdir = path.join(topdir, 'Podcast', artst, album)
    if title and genre:
        if 'podcast' in genre.lower():
            newfname = title + ".mp3"
    return (newdir, newfname)

def sanitize(s):
    if not s: return s
    return s.replace(':','-').replace('&','and')

def filerename(arg, dirname, fnames):
    if fnames:
        for fname in fnames:
            if (fname.lower()[-4:]=='.mp3'):
                newdir, newfname = getnewnames(dirname, fname)
                if newdir != dirname or newfname != fname:
                    newdir = sanitize(newdir)
                    newfname = sanitize(newfname).replace('/','')
                    oldfull = path.join(dirname, fname)
                    newfull = path.join(newdir, newfname)
                    print oldfull
                    print "   ", newfull
                    if not path.exists(newfull):
                        try:
                            os.mkdir(newdir)
                        except Exception, e:
                            print "dir error:", e
                        try:
                            os.rename(oldfull, newfull)
                        except Exception, e:
                            print "RENAME ERROR:", e

path.walk(maindir,filerename,None)
